### ISSUE TITLE
Cannot find variable: Symbol

### ISSUE THREAD

**Issue by buehler** [preboot/angular-webpack#62]
Hey there

I'm currently fooling around with your starter-project and I'm experiencing a weird error. When I'm using karma with PhantomJS (on windows, sadly) I get the following error from karma-shim.js:

```
29 03 2016 13:48:00.909:DEBUG [phantomjs.launcher]:   http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:7019 in getSymbolIterator
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:22950
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:22959
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:21763
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:21428
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:21371
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:21218
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20247
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:7273
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:7075
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:6368
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:6341
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:50
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:20 in __webpack_require__
  http://localhost:9876/base/karma-shim.js?c27e536eb59d08306e4207f2dd33c3315356eaa9:40

PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  ReferenceError: Can't find variable: Symbol
  at C:/pathToMyProject/karma-shim.js:7019 <- webpack:///~/angular2/src/facade/lang.js:408:0

```

That's the debug output of karma. When I use the Chrome-Launcher, everything works as expected but it's no use for any CI :-(

Cheers
Christoph

**Comment by buehler** [comment]
addition: build and web-dev-server and stuff does work!
Great work! :+1:

**Comment by ocombe** [comment]
What version of node do you use ?

**Comment by buehler** [comment]
node: 5.9
npm: 3.7.3

**Comment by ocombe** [comment]
Ok thanks, you're up to date so that's not the problem. Maybe something with the last beta or because @Foxandxss move the polyfills to a new external file and forgot to add it to karma ;-)
We'll check.

**Comment by Foxandxss** [comment]
Oh, my bad my bad.

**Comment by Foxandxss** [comment]
It is not that issue at the end. How are you running the tests? I haven't change anything for tests lately.

**Comment by buehler** [comment]
:) well I run `npm test`
which invokes `karma start` 

the karma config looks like this: 

```
var path = require('path');
var webpackConfig = require('./webpack.config');

module.exports = function(config) {
    var _config = {

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',

        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine'],

        // list of files / patterns to load in the browser
        files: [
            { pattern: './karma-shim.js', watched: false },
            { pattern: './src/**/*.spec.ts', watched: true, included: false }
        ],

        // list of files to exclude
        exclude: [],

        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
            './karma-shim.js': ['webpack', 'sourcemap']
        },

        webpack: webpackConfig,

        webpackMiddleware: {
            // webpack-dev-middleware configuration
            // i. e.
            stats: 'errors-only'
        },

        webpackServer: {
            noInfo: true // please don't spam the console when running in karma!
        },

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress'],

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_DEBUG,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,

        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['PhantomJS'], // you can also use Chrome

        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: true
    };

    config.set(_config);

};
```

**Comment by buehler** [comment]
the funny thing is, when I run the tests in Chrome, there is no problem, but when I run them in phantom, I get some errors.

**Comment by dobrud** [comment]
had the same issue yesterday and I've just switched to chrome

**Comment by buehler** [comment]
It's all nice and shiny to use chrome, but not really practicable on a CI environment :-/

**Comment by Foxandxss** [comment]
You shouldn't worry about CI because they run linux boxes. Still, I am checking if there is a known issue with phantom or the launcher.

**Comment by dobrud** [comment]
@buehler I got the tests working with chrome on Travis CI yesterday

**Comment by buehler** [comment]
I tested on my osx again. I get the same error:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Symbol
  at /Users/xxx/Documents/Development/angular2-seed/karma-shim.js:7067 <- webpack:///~/angular2/src/facade/lang.js:426:0
```

**Comment by MikaAK** [comment]
I get this when on Travis CI too

**Comment by gcorgnet** [comment]
Hey guys, running into the same issue with this. Has anyone got any success ?

**Comment by Foxandxss** [comment]
With a straight copy of the repo it doesn't happen. So I guess you modified something that somehow makes travis or karma to not transpile correctly.

**Comment by MikaAK** [comment]
I fixed this a couple weeks ago on my seed project, the solution is to add `babel-polyfill` and require it at the top of `karma-shim.js`. Hope this helps!

**Comment by buehler** [comment]
@MikaAK I'll try that as soon as possible

**Comment by bradleywhit** [comment]
I am getting the same error: 
ReferenceError: Can't find variable: console
At the localhost, still doesn't work

What do you mean by karma-shim.js??@MikaAK
Thanks

**Comment by Foxandxss** [comment]
Project changed a bit in a year. Open a new issue if this is still a problem
